name: sync-fork-and-deploy-coe

on:
  schedule:
    - cron: '0 0 * * 1' # every monday
  workflow_dispatch: # on button click
      
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    
    steps:
    - name: Sync to Upstream
      if: true == false
      uses: tgymnich/fork-sync@v1.8
      with:
        owner: microsoft
        head: main
        base: main

  deploy-coe:
    needs: sync-fork
    uses: ./.github/workflows/deploy-unmanaged-application.yml

    with:
      solution_name: CenterofExcellenceCoreComponents
      environment_url: https://org3213fbb2.crm.dynamics.com
      username: loic.cimon@loiccimon.com
    secrets:
      password: ${{ secrets.PASSWORD }}
